language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fI+jZsxcDYDRtTb/lYaYdvzIWag5uIbo9bUVCcLLLyVMJEC6DrN3gBENSl02CEeCUA8ZXBqWzlafSRZrOGdyjl3E0gio15V8TiDi1kkM6OLo6Ff8kpqIruLKp6XEWKPAm9qLbeqDbS7VtUHKkw/OtgHQQhJVwzTtaW9j/CsxgPSUjEdsetlFV+ckS6SN9XkALNaRpNkishhq7fO4UBkIg+CXoUWt8bdFH4547oYlHr8AzYPYnzbSN4ilMU69RfDFq3rcQNCcoy/MH9Wg8vKL23nAV9syO8dXFSKsLxyJhqtERFUW2cfx8VsmTJaX4LeabbJcMr/NArd4jX9I9SyTzcrG8KGR2bKtbyXp6h2FEk1D2HdgZaVkChDvJvjy6aL5XdArFHUcT+NG+X5vyLVjpEhKedsQireCK2AyXPtGqzT+FMJ+KSHEp4TxxhNWidiorJglRIin4Xq0/tezdPnTcML13yddcDQWlzqcL0wpWCUYCu0hB0xXxuNF19S2yADMWLw3BIxj/NWyTo5EJ82IuXiMaif3WkYNWOHMZ6MFqjGMIid9A6fNqZTKEBCaoULAGd1lRc8TbjHtrn9heZdMSwxft5n3iAP02iuD73kXOYFR1YZxCradfheLYcX+u1WUNqV6jzFhRk63VkzWpZ6KyboUIdIGJY6zwEpIYaZbOkE=
  file:
    - "retext-diacritics.js"
    - "retext-diacritics.min.js"
  on:
    tags: true
