language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JTnFUXgRf4jjsTjn6mmp6kHCOQJPkrTQyRIg+NABgZ35vE+hKyAytp2VoLX0uZ5DnSo3k1HW2F9VoBsJvHIqMYIfD26ma5VGwWqOJ/3aHfoIoWmdNvPMHYymLgXwr5qbmKq5bO3/CRY6obOv8H+wR0UZwW7hgpJOh/xJrRbPHkoCj9g+2V1j6xXefE//3YM6yd9JXXubslRzaEX8OLOIhh0Q0r1brtEedpYy4gzTuN7dbEQbLFLIB23aIKyU9O5XczliHR/PAO17sn22a5YFjb42zmZ4qOZGJ2IjKWn2K+Yb+h0dhcmh9L4YHu46PuG98cjeYt0kvHjp+7IBNjKg8rpiCxYKHL4lohoEtD7WwGrayx1oEleZ3S3lcVH9RFI7HllXJo4O8Swq4y+Nnh0vexJmlUHmudFmn7Y3bZZyMH52K5aPHeq+ZdYW2pVDRYwkre51bRQemFbhen5+ZWS5YxWsmhHQoXpIw/w0L7OXC/oR6CqQJ1uGDQrfCCAvmjg/qmWDVNNMvj4x1Jo3b9kKQRp8JA+I4mIDmKQWxx7unyyrIjDYAuyqNeNCt1gip6CC+SZ3bLQx2/meLg2x6KbJGxJcXb7AVZ5b/OGnM7au2oZnkoMluf8CV1Mr9MLs14dp4bHGINVg+J2D7db16OCIeiBlZ8Pgzq2TAZfIFUcqo2I=
  file:
    - "retext-diacritics.js"
    - "retext-diacritics.min.js"
  on:
    tags: true
