/** @type {Record<string, string>} */
export const schema = {
  // French.
  'beau ideal': 'beau idéal',
  boutonniere: 'boutonnière',
  'bric-a-brac': 'bric-à-brac',
  cafe: 'café',
  'cause celebre': 'cause célèbre',
  chevre: 'chèvre',
  cliche: 'cliché',
  'comsi comsa': 'comme ci comme ça',
  'comme ci comme ca': 'comme ci comme ça',
  consomme: 'consommé',
  "coup d'etat": "coup d'état",
  'coup de grace': 'coup de grâce',
  crudites: 'crudités',
  'creme brulee': 'crème brûlée',
  'creme de menthe': 'crème de menthe',
  'creme fraice': 'crème fraîche',
  'creme fresh': 'crème fraîche',
  crepe: 'crêpe',
  debutante: 'débutante',
  decor: 'décor',
  'deja vu': 'déjà vu',
  denouement: 'dénouement',
  facade: 'façade',
  fiance: 'fiancé',
  fiancee: 'fiancée',
  flambe: 'flambé',
  garcon: 'garçon',
  lycee: 'lycée',
  'maitre d': 'maître d',
  'menage a trois': 'ménage à trois',
  negligee: 'négligée',
  'papier-mache': 'papier-mâché',
  'paper mache': 'papier-mâché',
  'paper-mache': 'papier-mâché',
  protege: 'protégé',
  protegee: 'protégée',
  puree: 'purée',

  "raison d'etre": "raison d'être",
  'my resume': 'my résumé',
  'your resume': 'your résumé',
  'his resume': 'his résumé',
  'her resume': 'her résumé',
  'a resume': 'a résumé',
  'the resume': 'the résumé',
  risque: 'risqué',
  roue: 'roué',
  soiree: 'soirée',
  souffle: 'soufflé',
  soupcon: 'soupçon',
  touche: 'touché',
  'tete-a-tete': 'tête-à-tête',
  voila: 'voilà',
  'a la carte': 'à la carte',
  'a la mode': 'à la mode',
  emigre: 'émigré',

  // Spanish.
  'el nino': 'el niño',
  jalapeno: 'jalapeño',
  'la nina': 'la niña',
  'pina colada': 'piña colada',
  senor: 'señor',
  senora: 'señora',
  senorita: 'señorita',

  // Portuguese.
  acai: 'açaí',

  // German.
  doppelganger: 'doppelgänger',
  fuhrer: 'führer',
  gewurztraminer: 'gewürztraminer',
  ubermensch: 'Übermensch',

  // Latin.
  'vis-a-vis': 'vis-à-vis',

  // Swedish.
  filmjolk: 'filmjölk',
  smorgasbord: 'smörgåsbord',

  // Names, places, and companies.
  beyonce: 'beyoncé',
  bronte: 'brontë',
  'champs-elysees': 'champs-Élysées',
  citroen: 'citroën',
  curacao: 'curaçao',
  'haagen-dazs': 'häagen-dazs',
  'haagen dazs': 'häagen-dazs',
  lowenbrau: 'löwenbräu',
  monegasque: 'monégasque',
  'motley crue': 'mötley crüe',
  nescafe: 'nescafé',
  queensryche: 'Queensrÿche',
  quebec: 'québec',
  quebecois: 'québécois',
  Angstrom: 'Ångström',
  angstrom: 'ångström',
  skoda: 'Škoda'
}
